### ISSUE TITLE
Data folder is not written automatically

### ISSUE THREAD

**Issue by heimgreg** [Sync-my-L2P/Sync-my-L2P#100]
I'm using Sync-my-L2P on Ubuntu 16.04. It apparently tries to save the datafile to
`~/.local/share/Sync-my-L2P/Sync-my-L2P/data.xml`

The folders were not created automatically so I always got the message "Kursinformationen nicht speicherbar." when closing, see *l2pitemmodel.cpp*.

Now, I created `~/.local/share/Sync-my-L2P/` manually and the datafile could be written.

Maybe `QDir().mkdir(dataPath)` is only able to create one single instead of two nested folders.
If this is the case, the path would have to be divided and the existence of the folders would have to be checked individually.

**Comment by Sync-my-L2P** [comment]
Thanks for your hint. We will close the bug in the next version

**Comment by Sync-my-L2P** [comment]
Fixed in 99f219e29e366101736003eed560b398b2e4fafc

**Comment by Miladiir** [comment]
I have this exact error on Windows 10. Unfortunately I am unable to find the data path. Any help?

**Comment by heimgreg** [comment]
Try creating the folder "C:/Users/<USER>/AppData/Local/Sync-my-L2P" by hand. This might fix the problem until the new version with the code fix is released.
