### ISSUE TITLE
Linux: Need to login every time

### ISSUE THREAD

**Issue by heXXag0n** [Sync-my-L2P/Sync-my-L2P#103]
Hello there,
I'm experiencing the undesired behavior, that I am logged out every time I start the program. Not only that, it also doesn't save the configuration of the checkboxes under the 'Einstellungen' tab.

kind regards

**Comment by heXXag0n** [comment]
I 'fixed' the problem by running the program as root for once and then chowned the config file under ~/.config/Sync-my-L2P back to my regular user. Maybe this is helpful for others but I don't think it is the supposed way.

**Comment by justin-time** [comment]
Hi,
which linux os are you using and which package of Sync-My-L2P have you downloaded? 

This issue sounds like a problem with the directory permission of the ~/.config/Sync-my-L2P folder. I'm not sure if this is related to Sync-My-L2P.

Could you please rename the ~/.config/Sync-my-L2P to ~/.config/Sync-my-L2P-bak and check if SmL2P creates the directory ~/.config/Sync-my-L2P and the included files correctly?

**Comment by heXXag0n** [comment]
Hello, I did as you said. SmL2P vreated a new folder and this time it had no issues at all. Thanks, it seems that I messed up something prior.
Thanks and closed.
