### ISSUE TITLE
Error while fetching new data

### ISSUE THREAD

**Issue by PaulXiCao** [Sync-my-L2P/Sync-my-L2P#107]
Anytime I open the app this error message pops up:

**Beim Abruf des Inhalts einer Veranstaltung ist ein Fehler aufgetreten**
Error downloading https://www3.elearning.rwth-aachen.de/XXXX...
 server replied: Internal Server Error;
 {"Status":false,"errorDescription":"An unknown error occurred. Please report with the error id.<br\/>Original error: Der versuchte Vorgang ist unzulässig, weil er den vom Administrator erzwungenen Listenansicht-Schwellenwert überschreitet.","errorId":"69ca1cc6-a2fe-4268-931f-37740e6c9f1d"}

After some time the sync process keeps on going and it works fine.

**Comment by Sync-my-L2P** [comment]
This is an error caused by the L2P. Please report these message to the L2P
Team as stated in the error message.

2017-02-03 9:17 GMT+01:00 PaulXiCao <notifications@github.com>:
