### ISSUE TITLE
NoSuchFlowExecutionException

### ISSUE THREAD

**Issue by steffanson** [Sync-my-L2P/Sync-my-L2P#108]
Hi!

I installed the latest release of SyncMyL2P for Linux Wily Amd64 on my Ubuntu 17.04 machine;
however, when I click "Login" the RWTH-Page

> https://sso.rwth-aachen.de/idp/profile/SAML2/Redirect/SSO?execution=e2s1

opens and shows me the error `NoSuchFlowExecutionException` instead of the login. 
Therefore I cannot use the program. :-(

Cheers

**Comment by justin-time** [comment]
Could you please try the package sync-my-l2p_2.2.0-0-**xenial**_amd64.deb?
For me, I'm using this package and everything works fine on ubuntu gnome 17.04.

If this does not work, you could delete the folder "Sync-my-L2P" on ~/.config and ~/.local/share and give it a second try.

**Comment by steffanson** [comment]
> If this does not work, you could delete the folder "Sync-my-L2P" on ~/.config and ~/.local/share and give it a second try.

Unfortunately both didn't work and lead to the same error. I also tried it with a clean Firefox installation.

**Comment by severoraz** [comment]
@steffanson if I go to that URL I get the same error as you

**Comment by steffanson** [comment]
I close here for now until I narrowed down the issue as it seems to be a browser issue of the Firefox 53 on Kubuntu 17.04. I could reproduce it at another friends Kubuntu installation with similar settings; However on Chromium it works as expected.
