### ISSUE TITLE
Remember synchronization removed selections (blacklist)

### ISSUE THREAD

**Issue by severoraz** [Sync-my-L2P/Sync-my-L2P#109]
On the main view, under the Synchronization group, one can remove folders/files through the "Remove selection" action. However, after a program restart, the removed selections are forgotten.

This is an enhancement request for the removed selections to be saved and remembered in further startups.

**Comment by Sync-my-L2P** [comment]
Removed selections should be remembered. Probably this issue was caused by an error saving the program state.

**Comment by severoraz** [comment]
True, thanks for looking into it!
