### ISSUE TITLE
Error message on shutdown

### ISSUE THREAD

**Issue by SirWindfield** [Sync-my-L2P/Sync-my-L2P#110]
As soon as I close the program, the following error message appears:
`Kursinformationen nicht speicherbar. Das System kann den angegebenen Pfad nicht finden`. It only happens on my Windows PC aswell. 
The only thing that I changed was the directory into l2p syncs the files.

**Comment by claell** [comment]
I sometimes get the same message (I think as well on Ubuntu).

**Comment by PaulXiCao** [comment]
the program tries to save data to the following path (under linux): $HOME/.local/share/Sync-my-L2P
i read it in the logs (had to set the logging level to advanced.
after i created the folder everything worked smoothly: mkdir $HOME/.local/share/Sync-my-L2P

but dunno whats happening under windows

**Comment by ArathonV** [comment]
Fix for windows:
Create Folder:  
C:\Users\USERNAME\AppData\Local\Sync-my-L2P\Sync-my-L2P

**Comment by Sync-my-L2P** [comment]
Fixed in 99f219e29e366101736003eed560b398b2e4fafc
