### ISSUE TITLE
Problem with loggin in on Ubuntu (Browser does not open)

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#13]
Hi,
after compiling the version with the fix #12 manually and launching the program, a window opens saying the the browser will open soon. Unfortunately it does not open for me.

The log (after trying this several times) is:

>ERROR 12:00:02.208 Kann Daten von Festplatte nicht parsen:  "unexpected end of file" 
INFO  12:00:02.234 Erreichbarkeitsrequest 
INFO  12:00:02.675 Erreichbarkeit festgestellt 
ERROR 12:00:06.025 Unerwarteter Antwortstatus:  "error: unknown app id." 
INFO  12:00:10.016 Erreichbarkeitsrequest 
INFO  12:00:10.340 Erreichbarkeit festgestellt 
ERROR 12:00:13.471 Unerwarteter Antwortstatus:  "error: unknown app id." 
INFO  12:00:18.257 Erreichbarkeitsrequest 
INFO  12:00:18.570 Erreichbarkeit festgestellt 
ERROR 12:00:21.968 Unerwarteter Antwortstatus:  "error: unknown app id." 
INFO  12:00:44.822 Erreichbarkeitsrequest 
INFO  12:00:45.146 Erreichbarkeit festgestellt 
ERROR 12:00:48.638 Unerwarteter Antwortstatus:  "error: unknown app id." 
INFO  12:00:50.432 Erreichbarkeitsrequest 
INFO  12:00:50.650 Erreichbarkeit festgestellt 
ERROR 12:00:54.478 Unerwarteter Antwortstatus:  "error: unknown app id." 
INFO  12:01:16.746 Erreichbarkeitsrequest 
INFO  12:01:17.020 Erreichbarkeit festgestellt 
>ERROR 12:01:20.438 Unerwarteter Antwortstatus:  "error: unknown app id." 

So it seems that there is a problem opening the browser.

**Comment by claell** [comment]
When running the programm in QTCreator, the output from the application is:
>QSslSocket: cannot resolve SSLv2_server_method

**Comment by justin-time** [comment]
You need a ClientID for connecting with the RWTH-L2P-Servers. Unfortunately, the RWTH ITC does not allow to publish this ClientID. And so the source code comes without a ClientID!

**Comment by claell** [comment]
Ah, ok. So it is not easily possible to circumvent the waiting time with manually compiling the source code, I guess. Or can I manually insert an ID, for example the ID that I use to connect to the L2P with my browser? Is there a way to get this ID (if existing)?

**Comment by justin-time** [comment]
Correct! Without a change of mind of the ITC it will not be possible to compile sync-my-l2p on one's own. Sadly, we have to wait for the compiled linux app. Furthermore I think it would not be possible to use the ID of the L2P browser, because every app has it's own specific ID.

BTW: Which Linux OS are you using?

**Comment by claell** [comment]
Have you tried to use the ID of the browser? How does one find it out? I just looked through the cookies and played around a bit with FireBug, but I am not very experienced on this topic.

I am using Ubuntu 14.10 currently. And you?

**Comment by justin-time** [comment]
I haven't try to extract a ID yet…

I am using Ubuntu 14.04.

**Comment by claell** [comment]
Ok. Maybe it would be worth it, but one has to know, how to do it.
Anyway, it is very sad that the ITC is so closed-minded regarding this topic..

**Comment by Sync-my-L2P** [comment]
The API uses OAuth, while the website is using NTLM authentication. Therefore you cannot extract any  id from the website.
