### ISSUE TITLE
Download auf externe Festplatte schlägt fehl

### ISSUE THREAD

**Issue by jonaaix** [Sync-my-L2P/Sync-my-L2P#164]
Egal welche Dateien ich auswähle, selbst wenn es nur eine einzige ist, kommt die Fehlermeldung: "Fehler beim öffnen mit Schreibberechtigung."

```
INFO  15:49:58.084 Diese Version ist aktuell  ( 20402 ) 

INFO  15:49:58.098 L2P Erreichbarkeitsrequest 

INFO  15:49:58.100 Moodle Erreichbarkeitsrequest 

INFO  15:49:58.360 L2P erreichbar 

INFO  15:49:58.360 Moodle erreichbar 

INFO  15:50:02.581 Veranstaltungen empfangen 

INFO  15:50:04.150 Moodle-Veranstaltungen empfangen 

INFO  15:50:14.177 Setze Logging auf "Erweitert". 

DEBUG 15:50:16.436 Starte Download von https://moped.ecampus.rwth-aachen.de/proxy/api/v2/eLearning/Moodle/downloadfile/V01_Einführung in die Fertigungstechnik_kommentiert.pdf?downloadurl=/1084717/mod_resource/content/1/V01_Einführung in die Fertigungstechnik_kommentiert.pdf?forcedownload=1&token=3olXvtxwT2KtapwDYOF.....

ERROR 15:50:19.011 Fehler beim Öffnen mit Schreibberechtigung. :  V01_Einführung in die Fertigungstechnik_kommentiert.pdf 

```

**Comment by stormrider3106** [comment]
Versuch mal das Programm als Administrator zu öffnen

**Comment by jonaaix** [comment]
@stormrider3106 Das habe ich gemacht, der Fehler bleibt weiter. 
Ich habe den Downloadpfad standardmäßig auf eine andere Festplatte gesetzt (`E:\L2P_download`). Wenn ich `C:\Users\user\Downloads` als Verzeichnis setze, funktioniert der Download.
Mir ist noch aufgefallen, dass die andere Zielfestplatte im Ruhezustand war, als ich versucht habe sie über den Explorer aufzurufen. Dennoch hat der Download auch nach dem Aufwecken nicht funktioniert.

**Comment by RobertKrajewski** [comment]
I close this issue as this problem is very probably caused by the specific configuration of user rights on your external disk. SmL2P uses the ordinary ways/function calls to write files as the user that started the app.

**Comment by jonaaix** [comment]
Das Anlegen eines neuen Ordners auf der externen Festplatte löst das Problem. Jedoch bestand der vorherige Sync Ordner seit knapp 5 Jahren, eine aktive Änderung an Benutzerrechten wurde nicht vorgenommen. Es wäre hilfreich hier eine Aussagekräftige Fehlermeldung einzubauen.

**Comment by stormrider3106** [comment]
Das Problem ist Windowsseitig, daran kann SmL2P auch nichts machen. Windows gibt dazu auch keine näheren Informationen
