### ISSUE TITLE
Cannot download file

### ISSUE THREAD

**Issue by HarHarLinks** [Sync-my-L2P/Sync-my-L2P#168]
**Describe the bug**
```
ERROR 10:42:33.217 Directory not createable. :  Can not create the following directory: ss21/Funktionale Programmierung (VO) [12.53698]/Legal Notes on the Use of Zoom/CLS-Step-by-Step Guide for participants using zoom (EN) (PDF; Upload 02.03./ 
```
I'm not sure what is happening, since the file doesn't contain `/` on moodle:
![image](https://user-images.githubusercontent.com/2803622/114524863-e135ad80-9c45-11eb-8ac3-92575be9cd99.png)

**To Reproduce**
Sync https://moodle.rwth-aachen.de/course/view.php?id=14064 (Funktionale Programmierung (VO) [12.53698] SS21)

**Expected behavior**
Sync...

**Desktop (please complete the following information):**
 - OS: Arch 
 - Version aur/sync-my-l2p 2.4.2-1

**Comment by stormrider3106** [comment]
The filename is too long. File paths are limited to 128 characters if I remember correctly.

**Comment by HarHarLinks** [comment]
As far as I'm informed correctly, ext4 defines no maximum path length, but a "max. filename length" of 255 bytes.
"`CLS-Step-by-Step Guide for participants using zoom (EN) (PDF; Upload 02.03./`" is 76/77 characters long, equaling as much bytes when encoded with utf8.

The sudden slash inserted at the end makes me think it might be something else, but I haven't looked at the code. Either way, SyncMyL2P should really catch this case more gracefully.

**Comment by stormrider3106** [comment]
Technically, this repo isn't being updated anymore, as it has been passed to the RWTH [here](https://github.com/rwthmoodle/Sync-my-L2P). Also, SyncMyL2P handled file path length internally the last time I checked here.

**Comment by HarHarLinks** [comment]
Thanks, I saw that, but the fork only linked back to this issue section when I opened it. However it appears the fork has since opened their own issues. Looks like the new maintainers are still getting settled, since many links in the description and readme still link to here.
I'll move this report there.
