### ISSUE TITLE
Login Browser does not open

### ISSUE THREAD

**Issue by Gordin** [Sync-my-L2P/Sync-my-L2P#30]
I'm trying to login, but the Browser that is supposed to open for authentication just does not show up and the Login Window just switches to "Login fehlgeschlagen". I'm running archlinux and tried this with the latest version from master.

This is the log output:

ERROR 12:43:44.414 "Kann keine Daten von Festplatte laden" :  "No such file or directory" 
INFO  12:43:51.338 "Setze Logging auf "Erweitert"." 
INFO  12:43:54.095 "Erreichbarkeitsrequest" 
INFO  12:43:54.298 "Erreichbarkeit festgestellt" 
ERROR 12:43:57.604 Unerwarteter Antwortstatus:  "error: unknown app id." 
DEBUG 12:43:57.604 "Stoppe Login" 
DEBUG 12:44:00.939 "Stoppe Login"

**Comment by Sync-my-L2P** [comment]
Read the ReadMe.md or clientId.h before posting.

2015-02-12 12:51 GMT+01:00 Andreas Guth <notifications@github.com>:
