### ISSUE TITLE
Bug in "Fixed error in language switching."

### ISSUE THREAD

**Issue by justin-time** [Sync-my-L2P/Sync-my-L2P#31]
For me, the "Systemsprache" option does not work, the program falls back to English because there is a "/" in  if(!m_translator.load("/sync-my-l2p_" […] ) line 187 at mymainwindow.cpp.

See here: https://github.com/Sync-my-L2P/Sync-my-L2P/commit/d01775ae06a36450fad15926bcac69b895ce60e2

**Comment by Sync-my-L2P** [comment]
Thanks for the hint.
