### ISSUE TITLE
The "SSL/TSL" error catcher does not work every time!

### ISSUE THREAD

**Issue by justin-time** [Sync-my-L2P/Sync-my-L2P#36]
Most of the time, I receive your collected message but rarely I receive a normal SSL/TSL message.

Please take a look at my old commit 2bf40d085051b38e678bea428f8e068045abc296. This commit should be obsolete because of 7910fd13dd5e227e711de93eed55c737327b2c83, but it seems not to work correctly without it. 

The Problem is, that my commit also mute the SSL/TSL message and this is only suboptimal because in this case the user does not get your collected message.

**Comment by Sync-my-L2P** [comment]
Fixed in 2fa3b0e47a091db8678c00905f8c230deb352a86

**Comment by justin-time** [comment]
Thank you! It works!
