### ISSUE TITLE
Change location of data.xml on windows

### ISSUE THREAD

**Issue by Sync-my-L2P** [Sync-my-L2P/Sync-my-L2P#39]
For some people writing into the program install dir is not possible. Therefore the path should be adapted to a writable path.

**Comment by justin-time** [comment]
What's about:
`QString dataPath = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) % "/Sync-my-L2P/data.xml";`

This StandardPaths returns 
 * for Windows: "C:/Users/`<USER>`/AppData/Local", "C:/ProgramData"
 * for Linux: "~/.config"
 * for Mac: ""~/Library/Preferences"

Found here: http://doc.qt.io/qt-5/qstandardpaths.html

**Comment by justin-time** [comment]
QStandardPaths::AppLocalDataLocation is added in QT5.4!!!

Ubuntu 14.04 uses QT5.2 please use another QStandardPaths!!!!
