### ISSUE TITLE
Problem, when two folders with the same name exists

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#46]
When trying out the new beta, I experienced the issue that I have two folders/classes with the same name on L2P. In this case, both classes are synced into the same folder. This is not, what I would expect. Please add an option to select a different name for one of the classes.

```INFO  09:31:42.080 "Veranstaltung " "Kommunikation  und Organisationsentwicklung"  ( "14ws-02374" ") hinzugefügt." 

INFO  09:32:53.936 "Veranstaltung " "Kommunikation  und Organisationsentwicklung"  ( "14ws-03111" ") hinzugefügt."
```

**Comment by Sync-my-L2P** [comment]
For doing so you have to implement new features for the gui, create a database in the background for mapping your name to the real name, think about alle special cases (switched users, directory names, resets etc.).
As you can guess this is a lot of work. It also makes the program harder to maintain and the gui harder to understand. But only a few users would need this and therefore this is no solution.

**Comment by claell** [comment]
Ok, so if you are not implementing the renaming functionality (which is another thing that I would generally like, since a folder named ws14 is not my normal naming style), you could at least create two folders one named with a "1" or something else at the end. The current behaviour to copy everything into one single folder is not right and messes up the materials.

**Comment by claell** [comment]
Now I have this problem again with a course which is using two rooms with the same name. One for the lecture and one for the practice.

There are also files with the same name in both courses, so I have a similar problem like described in #96 now.

**Comment by auxua** [comment]
A rather simple approach could be, adding a suffix to the folder name like the cid - folders then have names like "Intro to Foo - 14ss-00003" - for simple legacy support, maybe starting with from a specific semester - or making this an option for the users...

At least, a simple request (viewAllCourseInfo e.g.) and then display a warning, that there is a shared folder for multiple courses could be an option...

**Comment by claell** [comment]
Also when I click on the course in L2P a different name is displayed on top:
![bildschirmfoto vom 2016-10-19 17-09-55](https://cloud.githubusercontent.com/assets/6171135/19524773/254517ea-961f-11e6-91fd-7e9e1e3fb060.png)
![bildschirmfoto vom 2016-10-19 17-09-48](https://cloud.githubusercontent.com/assets/6171135/19524774/254a2046-961f-11e6-93fa-c32e425a601b.png)
So maybe it is possible to get this names and use them instead.

**Comment by auxua** [comment]
The problem is, that the kind-information (V, Ü, P..) is not available in the API - these information come directly from Campus

**Comment by claell** [comment]
Ah, too bad.
