### ISSUE TITLE
Folders in "Medienbibliothek"

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#48]
Videos etc. in a "Medienbibliothek" are displayed within a folder containing the video. In my opinion that is not necessary and I would like to have all files from "Medienbibliothek" in one folder.

**Comment by Sync-my-L2P** [comment]
The program uses what the l2p api offers. Any further changes and hacks decrease drastically the maintainability.

**Comment by claell** [comment]
This would not be a hack, but changing, how files from "Medienbibliothek" are downloaded and displayed. I think it is annoying to have a seperate folder for every file, but if it is that, what the api offers and you can live with that, I am accepting it. Maye the api could be changed.
