### ISSUE TITLE
Crash on Ubuntu 14.04

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#51]
I accidentially installed the version for Ubuntu 14.10 and that crashed after login. Is there a way to prevent installing on wrong version of Ubuntu?

Edit: Installing the right version did not help, same error. I will try a reboot now.
Edit2: When starting via terminal, I get this:
```
clel@clel-Ubuntu-T400:~$ Sync-my-L2P 

(process:3103): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
It crashes after the "Speicherzugriffsfehler" message appears.

I also sent some reports via the bug reporting tool from Ubuntu, but I do not know, whether you are able to receive it.

**Comment by justin-time** [comment]
There is no way to prevent installing the wrong version. Maybe the next versions gets better version names like: sync-my-l2p_2.0.0-0~beta2~trusty.deb

Sorry, we can not use the ubuntu bug report tool.

I'm unable to reproduce this error. For me everything works fine. I've tested it on my main system and on a clean local machine.

**Comment by claell** [comment]
Thank you for the fast reply. I think that some .deb files have this option, that it is blocking install on wrong version.
Just tried it on my Windows Tablet, where it worked before and now it is not working on this device, either. Crashes after logging in and trying to get file list. Maybe it is an authentification problem. I have several instances of Sync-my-L2P authenticated. Will try to remove them.

**Comment by justin-time** [comment]
Ok now I can reproduce a crash but for me it happens after loggin in. But this is not a error of the ubuntu packages.

**Comment by claell** [comment]
Yes, I just thought it was. After removing all instances from the Online Auth page logging in worked. But I now get the following issue in the log:

ERROR 10:40:22.439 "Status der Kursinformationen nicht ok."

Might be related to a different problem, though. A course of me got reset to the earlier version of L2P, probably to be able to start a survey there. Now it is not correctly working with sync my l2p anymore. But yesterday it worked fine, so I am not sure, what caused this Error now.

**Comment by claell** [comment]
After restart of the program I got te crash again.

**Comment by justin-time** [comment]
Every Wednesday morning there is the maintenance of the L2P. Maybe they have "improved" the api or something else… Or something went wrong there…

**Comment by claell** [comment]
Now removing the authentification and trying tonlogin again, leads always to a crash. Cannot reproduce the steps that brought me the posted log error.

**Comment by claell** [comment]
Probably you are right. Do you have the same issue now?

**Comment by justin-time** [comment]
Ok this is strange… I've an very old version of my sync-my-l2p.conf and by using this everything works fine, but if I renew the authentication I have the same issue.

**Comment by claell** [comment]
Maybe the tokens they givenyou are not valid anymore and only the old ones work? I don't know, how the authentification works, though.

**Comment by justin-time** [comment]
Could you please test to uncheck every "Filter für Rubriken" except "Übungen". In this case it does not crash for me…

**Comment by claell** [comment]
You are right, now it does not crash for me, either.

**Comment by justin-time** [comment]
Ok, I know what happens… they really changed the API. 

It really looks like we have to change the source code of sync-my-l2p to fix it... 
One day after releasing the linux beta... this can not be true!

**Comment by claell** [comment]
Is it a big change?

**Comment by justin-time** [comment]
Not really, but I have to rebuild every linux package again… and I hope this is the last change of the API.

**Comment by Sync-my-L2P** [comment]
I hope it is not the last change of the API, but they will fix all the
inconsistencies and errors.
Nevertheless they should announces changes-

2015-02-25 11:13 GMT+01:00 Stefan Ahlers <notifications@github.com>:

**Comment by claell** [comment]
Hopefully you have set up an automatision (script) for creating the packages, or is that not possible. I saw that you already created a new issue regarding the api problem, so I am closing this issue.
