### ISSUE TITLE
Courses which use the old legacy L2P

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#52]
One course of me has been recently set to use the old legacy L2P. Now Sync-my-L2P does not work properly with this course anymore. It only displays the files that have been added before the change to legacy version. Is there a way to support such courses as well?

**Comment by Sync-my-L2P** [comment]
The API only supports the new l2p. There is no support for the old l2p or
any possibility to detect if a course belongs to the new or old version.

2015-02-25 11:00 GMT+01:00 Claudius Ellsel <notifications@github.com>:

**Comment by claell** [comment]
Ok, that is sad. If there would be a possibility to detect that, one could use modules from the old Sync-my-L2P to sync them, right? Would the old Sync-myL2P version work for that course?

**Comment by Sync-my-L2P** [comment]
The API doesn't give the user any information, whether this particular course is using the new or old l2p.
