### ISSUE TITLE
API change detected! Sync-my-L2P does not work anylonger!

### ISSUE THREAD

**Issue by justin-time** [Sync-my-L2P/Sync-my-L2P#53]
The filter options: "Lernmaterialien", "Gemeinsame Dokumente" and "Medienbibliothek" does not work any longer. 

Sync-my-L2P crashes because of an error of the urlParts.removeFirst(); in parser.cpp.

**Comment by justin-time** [comment]
I'm unable to fix the bug by adjusting the urlParts.removeFirst();

If I remove all urlParts.removeFirst(); it works but if there is only one urlParts.removeFirst(); it crashs...

**Comment by claell** [comment]
So as far as I could see, the url that comes from the api needs to be edited to be shown correctly? How does the url look like, maybe there is a different, more solid method to edit the url.

**Comment by Sync-my-L2P** [comment]
I tried to fix it in fdb2a87206c5def8563907f3a62ec6bafd6cb4cd.
But I am missing some types of materials due to the low number of courses I have. So somebody has to check if it really solves the problem.

**Comment by justin-time** [comment]
Everything works, except "Gemeinsame Dokumente".

**Comment by justin-time** [comment]
Should be fixed in #55.
