### ISSUE TITLE
Progress bar still has problems

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#70]
When downloading larger files (size displayed in MB) the progress bar jumps to a high value. After the download reaches 5 MB the bar jumps back and displays correct progress again. (see screenshots).
![bildschirmfoto vom 2015-05-31 19 41 41](https://cloud.githubusercontent.com/assets/6171135/7902966/77c69264-07cd-11e5-8285-2bd789bb153b.png)
![bildschirmfoto vom 2015-05-31 19 42 38](https://cloud.githubusercontent.com/assets/6171135/7902968/781f5bb0-07cd-11e5-8c3b-83311b964180.png)
![bildschirmfoto vom 2015-05-31 19 42 49](https://cloud.githubusercontent.com/assets/6171135/7902967/77ca09d0-07cd-11e5-9540-455bcf366d3b.png)

**Comment by justin-time** [comment]
Which ubuntu version and version of SmL2P are you using? What's the problem of the progress bar? I can not find a mistakes in the screenshots…

**Comment by claell** [comment]
I am using Ubuntu 15.04 and newest Linux release v.2.1.0

The problem is that for example the progress in the second screenshot appears before the one shown in the third one. The progress jumps immediately to 6 MB or a higher value (78 MB in second screenshot) and jumps back, when the download reaches 5 MB.

**Comment by justin-time** [comment]
Ok, I can confirm this bug. Tested on Ubuntu-GNOME 15.04 using sml2p v.2.1.0, too.

**Comment by Sync-my-L2P** [comment]
This bug is caused by correctSize() and correctUnit() in filedownloader.cpp.

2015-06-02 18:33 GMT+02:00 Stefan Ahlers <notifications@github.com>:

**Comment by claell** [comment]
Also when the progress bar is initialised a segment of the screen behind it is shown where the progress bar is for a little moment. Might be an issue with my setup and not sml2p, though.
