### ISSUE TITLE
Downloads bigger than 100 MB

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#71]
I tried to download a file bigger than 100 MB. Unfortunately the download freezes at 100 MB.
![bildschirmfoto vom 2015-05-31 19 53 09](https://cloud.githubusercontent.com/assets/6171135/7903020/7c19d20c-07cf-11e5-8c2c-71ace60e2aed.png)

**Comment by justin-time** [comment]
Sorry, I was unable to confirm this bug. First of all my biggest file is only 100,88 MB, but I was able to download this file. Unfortunately, I'm unable to reproduce it correctly. Are you sure that the file is not corrupted?

**Comment by claell** [comment]
You might be right. Now the download worked worked (only tried the download one time when the problem occurred). I also remember that I already downloaded files much larger than 100MB.
