### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by n0wis** [Sync-my-L2P/Sync-my-L2P#72]
A version compiled for ARM devices such as the Raspberry Pi would be nice

**Comment by Sync-my-L2P** [comment]
It would be nice, but only 3 people would use it.
Therefore it is too much effort.

Nevertheless you can compiled by yourself.

2015-06-03 10:47 GMT+02:00 n0wis <notifications@github.com>:

**Comment by n0wis** [comment]
Don't I need the client ID to do that?

**Comment by Sync-my-L2P** [comment]
I am not allowed to publish it.
But it is send in plain text to the l2p server during first login. You can
download a compiled version and extract it by a man-in-the-middle-attack.

2015-06-03 10:51 GMT+02:00 n0wis <notifications@github.com>:
