### ISSUE TITLE
Alternate reachability check

### ISSUE THREAD

**Issue by Sync-my-L2P** [Sync-my-L2P/Sync-my-L2P#75]
Use ping api function instead calling l2p main page

**Comment by justin-time** [comment]
Hmm… I think this would not work. The ping api function needs an accessToken and we want to test the reachability before login into. :-(

**Comment by auxua** [comment]
Just a small suggestion: 
You may use the API-Documentation page instead for calling. Some arguments:

* On generating the page, the API is testes internally (call will respond with error in case, the whole API is down)

* There can be circumstances, where the l2p mainpage is down/unreachable, while the API is still working 


Just to think about ;)

**Comment by MythicAngel** [comment]
L2P-API developer (me ;-) btw) reply: @auxua is correct. The Documentation page is served from the same server where the API is. So, if you call for Documentation page and get 200 status code in response, then surely the API server is functional.

This is the only solution until there is a dedicated server which API-Health status (like github, facebook etc.)
