### ISSUE TITLE
Update Benachrichtigung wird angezeigt + Hide-Option nicht speicherbar

### ISSUE THREAD

**Issue by Chrimby** [Sync-my-L2P/Sync-my-L2P#77]
Bei jedem Programmstart unter Windows und der ARM Version wird auf eine neue Programmversion hingewiesen, selbst wenn die aktuellste Version installiert ist. Außerdem bewirkt das Deaktivieren der Checkbox, ob nach Updates gesucht werden soll, nichts - beim nächsten Start wird dennoch hingewiesen.

**Comment by Sync-my-L2P** [comment]
Wenn die Hide Option nicht speicherbar ist, ist das nicht die neuste Version!
Das wird als Unterschied von 2.1.0 zu 2.1.1 angegeben.

**Comment by Chrimby** [comment]
(y)

Wird dieser Bug auch in der ARM Version behoben?

**Comment by justin-time** [comment]
Welches ARM Paket nutzt du denn genau? Funktioniert diese denn sonst normal? 

Die Ubuntu 15.04 Version zeigt den gleichen Fehler. Wahrscheinlich werden alle Linux Paket erneuert werden müssen und damit dann auch die ARM Versionen.

**Comment by Chrimby** [comment]
sync-my-l2p_2.1.1-0.trusty_armhf.deb mit Ubunu Mate 15.04 auf einem Raspberry. Und funktioniert soweit einwandfrei, bis auf das besagte Problem.

**Comment by justin-time** [comment]
Ah ok, gut zu hören, dass die sonst einwandfrei funktionieren. 

Der Fehler sollte eigentlich schon in der ARM Version behoben sein. Leider ist eine kleine Verwechselung beim Bau der Pakete passiert. In den nächsten Tagen wird eine aktualisierte Version für Linux und für die ARM Pakete erscheinen, dann sollte das alles funktionieren.

**Comment by Chrimby** [comment]
Ich kann dir nicht sagen, wie sinnvoll das ist, ich weiß nur, dass es funktioniert. Aus welchem Grund genau sollte man das nicht machen?

**Comment by justin-time** [comment]
Man kann nicht immer garantieren, dass alle Bestandteile, auf die das Programm aufsetzt abwärtskompatibel sind. Beispielsweise setzt Sync-my-L2P auf die externen Bibliotheken QT und auf libssl. 

Hier in diesem Fall ist es zwar gut gegangen, aber falls sich etwas grundlegendes an einer externen Bibliothek ändert, dann könnte es zu unvorhergesehenen Problemen kommen oder im schlimmsten Fall könnte man sich das komplette System zerschießen.

Deshalb sollte man zur Sicherheit immer nur das Paket verwenden, welches auch auf dem System erstellt wurde, welches man einsetzt.

Wenn die neuen Pakete hochgeladen sind, dann gibt es extra ein Paket sync-my-l2p_2.1.1-0.vivid1_armhf.deb das müsste dann perfekt zu deinem System passen.
