### ISSUE TITLE
Changed release files?

### ISSUE THREAD

**Issue by badboy** [Sync-my-L2P/Sync-my-L2P#78]
Hey, I'm the maintainer of the [AUR package for Sync-my-l2p](https://aur4.archlinux.org/packages/sync-my-l2p/) and recently hit an issue: The release files where changed. Not only where the file names changed (and thus the URL), but also the file content.

What are the reasons for these silent changes?

**Comment by Sync-my-L2P** [comment]
The release files were declared as v2.1.1, but the files were compiled from
v2.1.0 source files. After noticing this issue, the correct files were
uploaded.

2015-07-08 18:26 GMT+02:00 Jan-Erik Rediger <notifications@github.com>:

**Comment by badboy** [comment]
Thanks.

**Comment by justin-time** [comment]
Because of the strict version numbering scheme of debian packages,  the change of the version number was necessary.

Is it correct, that you are using the ubuntu vivid 32bit package to provide AUP packages?

**Comment by badboy** [comment]
Yip, because I'm too lazy to compile it and unpacking the deb is pretty easy.

**Comment by justin-time** [comment]
Oh, ok it's good to know that you are "reuse" the vivid packages. Thanks for your work!
