### ISSUE TITLE
Errors at start

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#79]
When sml2p fetches my courses, I get the following errors all with this description:

"Beim Abruf des Inhalts einer Veranstaltung ist ein Fehler aufgetreten"

```
Error downloading https://www3.elearning.rwth-aachen.de/_vti_bin/L2PServices/api.svc/v1/viewAllAnnouncements?accessToken=2u5EVN5Uxnuff7JqgRjw4NXrPBquj0VkTgnXtakFSxbUIMQa6lIfibcPK42OTWqm&cid=14ws-04543 - server replied: Internal Server Error;
 {"Status":false,"errorDescription":"An unknown error occurred. Please report with the error id.<br\/>Original error: Object reference not set to an instance of an object.","errorId":"3d8c5cac-4d7e-4029-b35a-ba35c7d0909d"}
```
```
Error downloading https://www3.elearning.rwth-aachen.de/_vti_bin/L2PServices/api.svc/v1/viewAllAnnouncements?accessToken=2u5EVN5Uxnuff7JqgRjw4NXrPBquj0VkTgnXtakFSxbUIMQa6lIfibcPK42OTWqm&cid=14ws-00748 - server replied: Internal Server Error;
 {"Status":false,"errorDescription":"An unknown error occurred. Please report with the error id.<br\/>Original error: Object reference not set to an instance of an object.","errorId":"bc17c908-40f4-4733-bd7c-64954c4da072"}
```
```
Error downloading https://www3.elearning.rwth-aachen.de/_vti_bin/L2PServices/api.svc/v1/viewAllAnnouncements?accessToken=PUm5Ps3hkxXQiGOewEwhhBrSr6nt9jes7XnxhABi7izvRoHYu9EAl0vZwEa7qOsZ&cid=14ws-09425 - server replied: Internal Server Error;
 {"Status":false,"errorDescription":"An unknown error occurred. Please report with the error id.<br\/>Original error: Object reference not set to an instance of an object.","errorId":"fcf09173-3e3c-4ac7-b6cc-1f8392311cc8"}
```
```
Error downloading https://www3.elearning.rwth-aachen.de/_vti_bin/L2PServices/api.svc/v1/viewAllAnnouncements?accessToken=2u5EVN5Uxnuff7JqgRjw4NXrPBquj0VkTgnXtakFSxbUIMQa6lIfibcPK42OTWqm&cid=15ss-06446 - server replied: Internal Server Error;
 {"Status":false,"errorDescription":"An unknown error occurred. Please report with the error id.<br\/>Original error: Object reference not set to an instance of an object.","errorId":"9263695c-5d2b-4f5d-9dd7-42a497d06c46"}
```

**Comment by justin-time** [comment]
It looks like a server problem because the server replied: "Internal Server Error".

For me, the error does not occurs. Could you please check, if the error occurs again later?

**Comment by claell** [comment]
It always occurs for me unfortunately. I think that this also happens on Windows. Probably there is an issue with some of my courses.

**Comment by Sync-my-L2P** [comment]
Does this error occur for courses which don't have any announcement? Then this message needs to be catched.

**Comment by claell** [comment]
I don't know. How can I see for which courses this error occurs? It shows at start. Maybe the log helps?

**Comment by Sync-my-L2P** [comment]
you can see the course id in the error message. E. g. : cid=14ws-04543. This id can also be found in the url of the according course room in the l2p

**Comment by claell** [comment]
No, at least one course which causes the issue has announcements.

**Comment by claell** [comment]
The courses are Mechanik I and II, Chemie and Einführung in den Maschinenbau. Actually all of them have announcements.

**Comment by auxua** [comment]
Hello Everybody,

I am one of the API Developers. Today I checked this issue and I think I know, when this comes up. This  error is caused by announcements without text bodies. We will fix this issue and try to deploy the fix as fast as possible (maybe next Wednesday). 

For better fixes, please provide some more information:

Did you use the Application before? If yes, since when exactly is this  error coming up?
Do you (or anybody) have more than these courses where the error comes up?

Have a nice day!

**Comment by claell** [comment]
Nice to read that you are aware of this issue. Also cool that you read here.

Yes, I used the application before. I don't know, since when the issue appears. I think it is since a few months (ca. 2).

The issue only comes up for the posted courses for me.

**Comment by auxua** [comment]
Actually, we are aware of this issue because someone wrote a mail today ;)

Nobody before told us about that so we did not know about it - with your information I will fix this bug on our test-servers and then aim for the deployment next wednesday - I think I know, what causes the problem internally.

**Comment by claell** [comment]
Alright. Thanks for fixing.

**Comment by auxua** [comment]
We had a deployment today and the bug is fixed - I testes the courses you mentioned and the API is working fine. :-)

**Comment by claell** [comment]
Yes, I can confirm that everything is working fine again. Thank you.

**Comment by claell** [comment]
Today I experienced something similar again:
![bildschirmfoto vom 2015-12-21 12-16-24](https://cloud.githubusercontent.com/assets/6171135/11929613/f9fda77c-a7dc-11e5-8077-ab4218b4c222.png)

**Comment by justin-time** [comment]
First of all, please open a new bug report for this issue! 

This is a know issue. This is because the old "Lernräume" are integrated into the new L2P but those modules are not activated at the moment.

**Comment by claell** [comment]
Will do.
