### ISSUE TITLE
file sync of assignment section is incomplete

### ISSUE THREAD

**Issue by debalance** [Sync-my-L2P/Sync-my-L2P#87]
Hi,
I noticed that from assignments only the task files are being downloaded, but not the provided example solutions.

**Comment by justin-time** [comment]
Hi,
thank you for your report. This is a known bug. But we can not fix it, because this is a bug in the L2P API.

**Comment by claell** [comment]
Do they know it as well and are fixing it at the moment?

**Comment by justin-time** [comment]
The assignment section is complete, now. SmL2P will support example solutions and corrections soon.
