### ISSUE TITLE
Wily version

### ISSUE THREAD

**Issue by claell** [Sync-my-L2P/Sync-my-L2P#89]
Hi, I am using Ubuntu 15.10 and unfortunately there is no deb package for this version, right now. Currently I am using the vivid version, which works as well, but maybe it is better to upload one for wily as well?

**Comment by justin-time** [comment]
They will be uploaded soon.

**Comment by claell** [comment]
Thanks. Is there any difference, why there need to be a specific package for every Ubuntu version?

**Comment by Sync-my-L2P** [comment]
ubuntu 15.10 version uploaded

**Comment by justin-time** [comment]
Sync-my-L2P depends on external libraries like Qt5. Every new ubuntu version comes with new updated versions of those libraries. To avoid conflicts, it is better to build sml2p for every ubuntu version.

**Comment by claell** [comment]
Ok, thanks for clarifying and uploading a version for wily.
