### ISSUE TITLE
Download on Webpage

### ISSUE THREAD

**Issue by jounathaen** [Sync-my-L2P/Sync-my-L2P#93]
The Webpage says "Die aktuelle Version für Mac OSX und Linux steht bald zur Verfügung" for several days now. On github, I can download the packages and run them. So why are they not linked to the webpage yet? 
Best regards - Jonathan

**Comment by Sync-my-L2P** [comment]
Because I don't have any time for this at the moment. After compiling the
OSX version, the webpage will be updated, too.

2016-01-30 15:20 GMT+01:00 Jonathan Klimt <notifications@github.com>:

**Comment by jounathaen** [comment]
Great! I couldn't use the software for several weeks, because first I didn't found the packages on github and compiling didn't work without the client key. (And it is so useful, that I don't want to miss it ;-) )
