### ISSUE TITLE
Provide download URL to always point to latest version

### ISSUE THREAD

**Issue by SirWindfield** [Sync-my-L2P/Sync-my-L2P#97]
I would really like to add Sync-My-L2P to 'homebrew-cask', a repository that provides programs and application in a similar fashion as 'apt-get'. Providing a URL that always points to the latest version of the application would make it much easier to auto-update the app from homebrew itself.
Maybe something like 

> https://github.com/Sync-my-L2P/Sync-my-L2P/releases/download/latest/SyncMyL2P-2.2.0-osx.dmg

**Comment by Sync-my-L2P** [comment]
Github already provides a link to the latest release: "https://github.com/Sync-my-L2P/Sync-my-L2P/releases/latest". But I guess, that the version description in the specific file "-2.2.0-" has to be removed, hasn't it?

**Comment by SirWindfield** [comment]
Not sure, I will try to create a cask now...

**Comment by SirWindfield** [comment]
Ok, I made a pull request and added the program to the home-brew cask tap. 
Users with home-brew installed can now install sync-my-l2p with the following commands:
`brew tap caskroom/cask` followed by `brew cask install sync-my-l2p`. Updating the program will work with the command `brew update` to update the program formula, followed by `brew upgrade` to upgrade the program itself.
You might add some information to the README file for people that may have home-brew.

**Comment by Sync-my-L2P** [comment]
Fixed in 418d46d733c15acc103ad97b3994706fc8e45f59
