### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by rleh** [Sync-my-L2P/Sync-my-L2P#99]
I am not able to login using sync-my-l2p version 2.2.0 (fc23 build; `sync-my-l2p-2.2.0-9.1.x86_64`) on my fedora 24.

My browser (Firefox 48.0) opens and show the following page [https://login.rz.rwth-aachen.de/idp/Authn/UserPassword](https://login.rz.rwth-aachen.de/idp/Authn/UserPassword):
```
Fehler: Der direkte Zugriff auf diese Seite ist nicht unterstützt. Bitte stellen Sie sicher, dass Sie diese Seite nicht direkt aufrufen, indem Sie ein Lesezeichen, den Zurück-Knopf des Browsers oder einen Eintrag im Verlauf nutzen. Um sich bei einem Dienst anzumelden, besuchen Sie bitte zuerst die Seite des Dienstes.
Error: Direct access to this page is not supported. Please ensure that you did not bookmark this page or reach it by using the back button or selecting it from your browser history. To log in to a particular service, please visit that service first.
```

The sync-my-l2p login dialog then says `Login filed.`

**Comment by Sync-my-L2P** [comment]
Please add an extended logfile

2016-08-11 14:22 GMT+02:00 Raphael Lehmann <notifications@github.com>:

**Comment by Sync-my-L2P** [comment]
No log provided

**Comment by rleh** [comment]
Sorry for the delay in replying, but here is an *advanced* log:
```
ERROR 21:15:46.019 Kann keine Daten von Festplatte laden :  No such file or directory 
INFO  21:15:46.190 This version is up to date  ( 20200 ) 
INFO  21:15:58.733 Set logging to "Advanced" 
INFO  21:16:10.530 Accessibility Request 
INFO  21:16:10.605 Accessibility ascertained.   
DEBUG 21:16:13.991 Open browser for verification. Url:  QUrl(https://oauth.campus.rwth-aachen.de/manage/?q=verify&d=5EQDZZFU8V) 
DEBUG 21:16:18.974 error: authorization pending. 
DEBUG 21:16:23.950 error: authorization pending. 
DEBUG 21:16:28.958 error: authorization pending. 
DEBUG 21:16:33.950 error: authorization pending. 
DEBUG 21:16:38.958 error: authorization pending. 
DEBUG 21:16:43.951 error: authorization pending. 
```

**Comment by Sync-my-L2P** [comment]
If you are able to login after copying the link I guess there is a problem with your browser. Is there any script/redirection blocking?

**Comment by rleh** [comment]
I use NoScript in Firefox, but without NoScript the problem persists.

I fixed the Problem by setting Firefox to my default browser manually:
`KDE System Settings` -> `Default Applications` -> `Web Browser` -> `Default Component` -> `Open http and https URLs` -> `[x] in the following browser:` -> select firefox.
